### ISSUE TITLE
Please add license file and consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [erwanjugand/oh-my-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

It also doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by erwanjugand** [comment]
Hello @unixorn, thanks for your feedback! 

I renamed the theme and added an MIT license.

You can add the theme on awesome-zsh-plugins :)
